
---

  - name: Installing requirements
    package:
      name: firewalld
      state: present
  
  - name: Starting Firewalld service
    systemd: name=firewalld enabled=yes state=started
  
  - name: Creating directories
    file:
      path: "{{ item }}"
      mode: 0775
      state: directory
    with_items:
      - /opt/firewalld-gsync/bin
      - /opt/firewalld-gsync/etc

  - name: Copy firewalld-gsync script
    copy:
      src: ./files/firewalld-gsync
      dest: "/opt/firewalld-gsync/bin/gsync"
      owner: root
      group: root
      mode: 0755

  - name: Check that the whitelist.url exists
    stat:
      path: /opt/firewalld-gsync/etc/whitelist.url
    register: whitelist

  - name: Configuring Google spreadsheet url
    lineinfile:
      path: /opt/firewalld-gsync/etc/whitelist.url
      line: "{{ gdoc_url }}"
      create: yes
    when: whitelist.stat.exists == False

  - name: Configuring crontab
    cron:
      name: Firewalld Google spreadsheet whitelist
      job: "/opt/firewalld-gsync/bin/gsync > /dev/null"
