
---

  - name: Installing requirements
    package:
      name: firewalld
      state: present
  
  - name: Starting Firewalld service
    systemd: name=firewalld enabled=yes state=started
  
  - name: Creating directories
    file:
      path: "{{ item }}"
      mode: 0775
      state: directory
    with_items:
      - /opt/firewalld-googledoc/bin
      - /opt/firewalld-googledoc/etc

  - name: Copy firewalld-googledoc script
    copy:
      src: ./files/firewalld-googledoc.sh
      dest: "/opt/firewalld-googledoc/bin/firewalld-googledoc"
      owner: root
      group: root
      mode: 0755

  - name: Configuring Google spreadsheet url
    lineinfile:
      path: /opt/firewalld-googledoc/etc/whitelist.url
      line: "{{ gdoc_url }}"
      create: yes
     
  - name: Configuring crontab
    cron:
      name: Firewalld Google spreadsheet whitelist
      job: "/opt/firewalld-googledoc/bin/firewalld-googledoc > /dev/null"
