
---

  - name: Installing requirements
    package:
      name: firewalld
      state: present
  
  - name: Starting Firewalld service
    systemd: name=firewalld enabled=yes state=started
  
  - name: Creating directories
    file:
      path: "{{ item }}"
      mode: 0775
      state: directory
    with_items:
      - /opt/fwdgdoc/bin
      - /opt/fwdgdoc/etc

  - name: Copy fwdgdoc script
    copy:
      src: ./files/fwdgdoc.sh
      dest: "/opt/fwdgdoc/bin/fwdgdoc"
      owner: root
      group: root
      mode: 0755

  - name: Configuring Google spreadsheet url
    lineinfile:
      path: /opt/fwdgdoc/etc/whitelist.gdoc
      line: "{{ gdoc_url }}"
      create: yes
     
  - name: Configuring crontab
    cron:
      name: Firewalld Google spreadsheet whitelist
      job: "/opt/fwdgdoc/bin/fwdgdoc > /dev/null"
