
---

  - name: Creating directories
    file:
      path: "{{ item }}"
      mode: 0775
      state: directory
    with_items:
      - /opt/fwdgdoc/bin
      - /opt/fwdgdoc/etc

  - name: Copy fwd-gdoc script
    copy:
      src: ./files/fwdgdoc.sh
      dest: "/opt/fwdgdoc/bin/fwgdoc"
      owner: root
      group: root
      mode: 0755

  - name: Configuring Google spreadsheet url
    lineinfile:
      path: /opt/fwdgdoc/etc/whitelist.gdoc
      line: "{{ gdoc_url }}"
      create: yes
      

